CREATE DATABASE IF NOT EXISTS effem CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE effem;

CREATE TABLE IF NOT EXISTS tasks (
    id          INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title       VARCHAR(100) NOT NULL,
    description TEXT,
    status      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE USER 'junior'@'%' IDENTIFIED BY 'junior';

GRANT SELECT, INSERT, UPDATE, DELETE ON effem.* TO 'junior'@'%';
