openapi: 3.0.0

info:
  title: Task Manager API
  description: API for managing tasks
  version: 0.0.1

servers:
  - url: http://localhost:8080/api

paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                      example: Reading
                    description:
                      type: string
                      example: Read Harry Potter
                    status:
                      type: integer
                      example: 0
        '400':
          description: Bad request
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Reading
                description:
                  type: string
                  example: Read Harry Potter
                status:
                  type: integer
                  example: 0
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  message:
                    type: string
                    example: Task created successfully
        '400':
          description: Bad request
  /tasks/{id}:
    get:
      summary: Get task by ID
      parameters:
        - name: id
          in: path
          description: task ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                    example: Reading
                  description:
                    type: string
                    example: Read Harry Potter
                  status:
                    type: integer
                    example: 0
        '404':
          description: Task not found
    put:
      summary: Update task by ID
      parameters:
        - name: id
          in: path
          description: task ID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Reading
                description:
                  type: string
                  example: Read Harry Potter
                status:
                  type: integer
                  example: 0
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task updated successfully
        '400':
          description: Bad request
    delete:
      summary: Delete task by ID
      parameters:
        - name: id
          in: path
          description: task ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task deleted successfully
        '400':
          description: Bad request
